services:
  backend:
    image: fastapi
    build: backend
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    volumes: 
      - ./backend:/app
    ports:
      - 5000:5000
    env_file: .env

  frontend:
    build: frontend
    volumes: 
      - ./frontend:/app
    ports: 
      - 3000:3000
    env_file: .env