services:
  backend:
    image: fastapi
    build:
      context: backend
      dockerfile: dockerfile.prod
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports: 
      - 8000:8000
    env_file: .env

  frontend:
    build:
      context: frontend
      dockerfile: dockerfile.prod
    ports: 
      - 3000:80
    env_file: .env